// Plot stage of the largeRJetAnalysisAndRates split (largeRJetSplitPlan.md).
//
// Loads each configured pair's merged state file
//   /data/larsonma/LargeRadiusJets/largeRJetIntermediateState/<taggerBase>__state.root
// in place of running the two big background event loops, then does everything else the
// monolithic macro did — signal loops, threshold derivations, scans, turn-ons, every
// per-file and overlay PDF — with the identical code path.
//
// Usage (after the usual ATLAS env + lsetup root):
//   root -b -l -q 'largeRJetPlot.C'
//
// WORKFLOW: generate the pair list ONCE with
//     cd ../condor && python3 submit_largeRJetCompute.py --pairs-only        # all pairs
// and from then on choose what to plot by editing kPlotSelect below — the pair list does
// not need regenerating to change a study. Any subset/ordering works against
// already-computed state, because state files carry no pair index.
//
// Prerequisite: compute run and hadd'd for every SELECTED pair. A missing state file is a
// fatal error, as is a missing histogram inside one.
// Known plot-stage gap vs the monolith: the five background event-display PDFs
// (displayEv*Back_) are not produced — their per-event geometry only exists while the
// background loops run.
#include "largeRJetAnalysisCore.h"

// =========================================================================================
// WHICH PAIRS TO PLOT / OVERLAY  — edit kPlotSelect below, never the pair-list file.
// =========================================================================================
//
// HOW MATCHING WORKS
//   Each entry is a plain SUBSTRING test (no globs, no regex), applied to one string per
//   pair: its description + its signal tagger path + its background tagger path.
//     * entries are AND-ed  -> a pair must match EVERY entry to be kept
//     * inside one entry, '|' separates ALTERNATIVES that are OR-ed
//     * {} (empty) keeps every pair in the list
//   So { "ggF", "rMerge_0.001|rMerge_2" } = "ggF, at either d_search".
//   Listing "rMerge_0.001" and "rMerge_2" as two SEPARATE entries matches NOTHING —
//   that asks for one file that is at both d_search values simultaneously.
//
// THE VOCABULARY IS WHATEVER IS IN THE PAIR LIST
//   The list is generated by  condor/submit_largeRJetCompute.py --pairs-only [--pu 140].
//   Run this macro once and read the "[pairs] pair N: ..." lines it prints — that IS the
//   text being matched. Two forms are available for most things:
//
//     concept        description form            filename form
//     -----------    ------------------------    -----------------------------
//     process        sample=ggF_hh_bbbb          HHbbbb_HLLHC
//                    sample=ttbar_allhad         ttbar_hdamp258p75_allhad
//                    sample=Zprime_ttbar_allhad_flatpT   flatpT_Zprime_tthad
//     pileup         PU140  /  PU200             r16129 (=PU140) / r16130 (=PU200)
//     d_search       rMerge=0.001 / rMerge=2     rMerge_0.001 / rMerge_2
//     input object   IO=gepCellsTowers           _IO_gepCellsTowers
//                    IO=gepWTAConeCellsTowersJets
//     seed           Seed=gFEXSRJ                Seed_gFEXSRJ
//                    Seed=jFEXSRJ                Seed_jFEXSRJ
//                    Seed=gepWTAConeCellsTowersJets   Seed_gepWTAConeCellsTowersJets
//     PU suppression SK / EtaSK / NoSK           _SK_ / _EtaSK_ / _NoSK_
//     subjet E_T     subjetEt=25 / =30 / =35     subjetEt25GeV / subjetEt35GeV
//     n input obj.   IOs=8 / IOs=128             _IOs_8_ / _IOs_128_
//     algo version   v2 / v3                     _v2.root / _v3.root
//
//   CAUTION on substrings: "SK" is contained in "EtaSK" and "NoSK", so "SK" alone matches
//   all three. Use the filename form "_SK_" when you mean plain SoftKiller only. Likewise
//   "rMerge=2" also appears inside "rMerge=25" if such a config is ever added.
//
// WHAT ACTUALLY EXISTS ON DISK RIGHT NOW (checked 2026-08-24)
//   PU140 (r16129): 6 configs — all are _SK_, IOs=128, IO=gepCellsTowers, v3.
//                   seeds gFEXSRJ(25) / gepWTAConeCellsTowersJets(25) / jFEXSRJ(35),
//                   each at rMerge 0.001 and 2.  There are NO r16129 _EtaSK_ outputs,
//                   and no IOs=8 / v2 outputs.
//   PU200 (r16130): 17 configs — includes EtaSK, IOs=8, v2 and the jFEX subjetEt scan
//                   (25/30/35/40).
//   A selection naming EtaSK or PU200 against a PU140 pair list therefore matches nothing:
//   regenerate the list with --pu 200 first.
//
// OVERLAYING PU140 AGAINST PU200
//   A pair list generated with --pu 140 or --pu 200 holds ONE pileup, so no selection can
//   produce a cross-pileup overlay from it. Generate the list with BOTH instead:
//       cd ../condor
//       python3 submit_largeRJetCompute.py --pairs-only --pu both --label pu140vs200
//   The plot stage then detects the mixed run automatically: each legend entry gets
//   "<PU> = 140" / "= 200" appended, and the ATLAS info line reads "<PU> = 140, 200"
//   instead of naming one of them (see overlayMixesPileup in the core).
//   Beware: PU140 has only the _SK_, IOs=128, v3 configs, so pin those in the selection
//   or the two pileups will not be like-for-like. This gives a clean 4-curve overlay
//   (PU140 and PU200, each at both d_search):
//       { "sample=ggF_hh_bbbb", "Seed_gepWTAConeCellsTowersJets", "_SK_", "_IOs_128_" }
//
// WORKING EXAMPLES
//   { }                                            everything in the list
//   { "sample=ggF_hh_bbbb" }                       one process, all its configs
//   { "ggF", "rMerge_0.001|rMerge_2" }             ggF, both d_search values (PU140-safe)
//   { "ggF", "Seed_gepWTAConeCellsTowersJets" }    ggF, cone-jet seed, both d_search
//   { "ggF", "Seed_gFEXSRJ|Seed_jFEXSRJ" }         ggF, FEX seeds only
//   { "PU200", "_EtaSK_", "rMerge_2" }             PU200 EtaSK with midpoint seeding
//   { "ttbar_allhad", "r16130", "_IOs_128_" }      ttbar at PU200, 128 input objects
//   { "sample=ggF_hh_bbbb", "Seed_gepWTAConeCellsTowersJets",
//     "_SK_", "_IOs_128_" }                        PU140 vs PU200 (needs --pu both list)
//
// COMMON MISTAKES
//   "Seed_WTACone"   -> not a real substring; use "Seed_gepWTAConeCellsTowersJets"
//   "PU200" + PU140  -> regenerate the pair list with --pu 200
//   "EtaSK" + PU140  -> no such outputs exist; use "_SK_"
//   two rMerge_*     -> use one entry with '|'
//
// ALWAYS build the pair list with --pu both, then pin the pileup HERE with "r16130"
// (PU200) or "r16129" (PU140). One list then serves every study, cross-pileup ones
// included, and switching pileup never means regenerating it:
//     cd ../condor && python3 submit_largeRJetCompute.py --pairs-only --pu both
// A list built with --pu 140 or --pu 200 holds ONE pileup, and then no selection can
// produce a cross-pileup overlay — that is what silently gave a PU140-only plot on
// 2026-08-25.
//
// ACTIVE MODE: the input-object comparison, moved to PU140 (r16129) while the PU200 samples
// are out of the way.  [3 pairs — see the arm list on the selection itself]
// ACTIVE MODE (superseded): NOMINAL v3 algorithm at PU200, both d_search values.  [2 pairs]
// Why each entry is here:
//   sample=ggF_hh_bbbb            one process — drop it for all three (x3 curves)
//   r16130                        PU200 only (r16129 = PU140; omit both for a
//                                 cross-pileup overlay, see mode (4))
//   _IOs_128_                     nominal input-object count (excludes the new 256s)
//   _IO_gepCellsTowers            towers as input objects
//   Seed_gepWTAConeCellsTowersJets  WTA cone-jet seeding
//   _EtaSK_                       eta-dependent SoftKiller — the standard PU suppression.
//                                 Substrings do not collide: "_EtaSK_" matches only
//                                 EtaSK, "_SK_" only plain SK, "_NoSK_" only NoSK.
//   _v3.root                      version 3 algorithm
// Both d_search values are included by NOT constraining rMerge at all.
// The legends label themselves: mixing IOs or versions appends "IOs = N" / "vN"
// (overlayMixesNIOs/Version); mixing pileups appends "<PU> = 140"/"= 200" and sets the
// ATLAS line to "<PU> = 140, 200" (overlayMixesPileup).
/*const std::vector<std::string> kPlotSelect = {
    "sample=ggF_hh_bbbb",
    "r16130",
    "_IOs_128_",
    "_IO_gepCellsTowers",
    "Seed_gepWTAConeCellsTowersJets",
    "_EtaSK_",
    "_v3.root"
};*/

// Contiguous middle of every tagger filename in this study, between the IO count and the
// PU-suppression tag. Those two fields are what distinguish the arms below but are NOT
// adjacent in the name, so an order entry that pins both has to span this.
const std::string kSeedMid =
    "_Seeds_2_R2_1.21_IO_gepCellsTowers_Seed_gepWTAConeCellsTowersJets";

const std::vector<std::string> kPlotSelect =
// ACTIVE: the same input-object comparison at PU140 (r16129), while the PU200 samples are
// temporarily off disk. ggF HH->4b, seeded-cone only (rMerge_0.001 = d_search disabled), v3,
// towers in, cone-jet seeds.
//
// PU140 does NOT carry the same grid as PU200, so this is not the 7-arm selection with the
// r-tag swapped — that would silently keep only 3 of its arms. Everything that exists at
// PU140 under the rest of this selection, verified against the pair list on 2026-09-11:
//     IOs=128  EtaSK T0      IOs=256  EtaSK T0
//     IOs=128  EtaSK T2      IOs=256  EtaSK T2
//     IOs=128  SK    T2
// i.e. 5 pairs, all with merged state. There is NO _SK_T0_ and no _NoSK_ of any kind at
// PU140, so the NoSK/SK-at-T0 arms of the PU200 study cannot be reproduced here without
// running the emulator for them first.
// The OR alternatives are mutually exclusive because each needs the underscore immediately
// before its tag: "_SK_T2_" does not match "_EtaSK_T2_" (an 'a' precedes SK).
{ "sample=ggF_hh_bbbb", "r16129", "rMerge_0.001",
           "_IO_gepCellsTowers", "Seed_gepWTAConeCellsTowersJets", "_v3.root",
           "_EtaSK_T0_|_EtaSK_T2_|_SK_T2_" };
// PU200 version of the same study, 7 arms: the 2 GeV input-tower cut (_T2_ applied / _T0_
// removed) crossed with the PU suppression (NoSK / SK / EtaSK) and the input-object count
// (128 / 256). Restore this once the PU200 samples are back.
//   _T2_ arm: ONE point only (IOs_128, EtaSK). At T2 the object-count cap never bound —
//             objectsProcessed was overwritten by the surviving-tower count — so IOs_256 was
//             a byte-for-byte duplicate of IOs_128 and adds nothing. SK/NoSK at T2 exist only
//             at 128 and are left out to keep the baseline a single curve.
//   _T0_ arms: all six of {NoSK, SK, EtaSK} x {128, 256}, where the IO count is a real knob.
// Verified 2026-08-28 to keep exactly 7 pairs, all with merged state.
/*{ "sample=ggF_hh_bbbb", "r16130", "rMerge_0.001",
           "_IO_gepCellsTowers", "Seed_gepWTAConeCellsTowersJets", "_v3.root",
           "_EtaSK_T0_|_SK_T0_|_NoSK_T0_|IOs_128" + kSeedMid + "_EtaSK_T2_" };*/
// 2 GeV cut comparison, EtaSK only at 256 IOs — the 2-arm version of the above.
/*{ "sample=ggF_hh_bbbb", "r16130", "rMerge_0.001", "_EtaSK_",
           "_IO_gepCellsTowers", "Seed_gepWTAConeCellsTowersJets",
           "_IOs_256_", "_v3.root", "_T0_|_T2_" };*/
// Z' -> ttbar [all-hadronic, flat pT], SINGLE configuration: seeded-cone only
// (rMerge_0.001 = d_search disabled), v3, 128 IOs, towers in, cone-jet seeds, EtaSK, PU200.
// Verified 2026-08-25 to keep exactly 1 pair; both its inputs exist (the background state
// file is shared with the ggF studies, and the Z' signal tagger output is on disk).
// _IOs_128_ is what pins it to one: the same configuration also exists at 256 IOs.
// NOTE: only the _T2_ production has this sample; there is no _T0_ Z' tagger output.
/*{ "sample=Zprime_ttbar_allhad_flatpT", "r16130", "rMerge_0.001", "_EtaSK_",
           "_IO_gepCellsTowers", "Seed_gepWTAConeCellsTowersJets",
           "_IOs_128_", "_v3.root" };*/
/*{ "sample=ggF_hh_bbbb", "r16130", "rMerge_0.001", "_EtaSK_",
           "Seed_gepWTAConeCellsTowersJets", "_IOs_8_|_IOs_128_"};*/
/*{ "sample=ggF_hh_bbbb", "r16130", "_EtaSK_", "_IO_gepCellsTowers", "rMerge_0.001",
           "Seed_gepWTAConeCellsTowersJets", "_v3.root", "_IOs_128_|_IOs_256_" };*/
/*{ "sample=ttbar", "r16130", "_IOs_128_",
           "rMerge_2", "_v3.root",
           "Seed_gepWTAConeCellsTowersJets_EtaSK_subjetEt25GeV"
           "|Seed_gFEXSRJ_EtaSK_subjetEt25GeV"
           "|Seed_jFEXSRJ_EtaSK_subjetEt40GeV" };*/


/*{ "sample=ggF_hh_bbbb", "_IOs_128_", "rMerge_0.001", "_IO_gepCellsTowers",
           "Seed_gepWTAConeCellsTowersJets", "_EtaSK_", "_v3.root" };*/

/*{ "sample=ggF_hh_bbbb", "r16130", "rMerge_0.001", "_EtaSK_",
           "Seed_gepWTAConeCellsTowersJets", "_IOs_8_|_IOs_128_" };*/
/*{
    "sample=ttbar",
    "r16130",
    "_IOs_128_",
    "_IO_gepCellsTowers",
    "Seed_gepWTAConeCellsTowersJets",
    "_EtaSK_",
    "_v3.root"
};*/
//|sample=ttbar_allhad


// ---------------------------------------------------------------------------------------
// READY-MADE ALTERNATIVE MODES — swap one in for kPlotSelect above.
// Every pair count below was verified against the files on disk on 2026-08-25.
// All assume a pair list built with:  submit_largeRJetCompute.py --pairs-only --pu both
//
// (1) INPUT-OBJECT COUNT: 128 vs 256  [4 pairs: 2 IOs x 2 d_search, ggF, PU200]
//     overlayMixesNIOs appends "IOs = 128"/"= 256" to the legend automatically.
//     Also exists at PU140 — swap r16130 -> r16129, or drop the r-tag entry for all 8.
//         { "sample=ggF_hh_bbbb", "r16130", "_EtaSK_", "_IO_gepCellsTowers",
//           "Seed_gepWTAConeCellsTowersJets", "_v3.root", "_IOs_128_|_IOs_256_" }
//
// (2) SEEDING: gFEX vs jFEX vs WTA cone  [6 pairs: 2 samples x 3 seeds, PU200]
//     v3, d_search = 2, IOs = 128, EtaSK, with a PER-SEED subjet E_T threshold:
//     jFEX at 40 GeV, cone and gFEX at 25 GeV.
//     The seed name and its threshold are ADJACENT in the tagger filename
//     ("Seed_jFEXSRJ_EtaSK_subjetEt40GeV"), so one OR-group can pin a different
//     threshold per seed — which a separate "subjetEt.." entry could not do, since that
//     would apply the same value to all three. This also makes the _EtaSK_ entry
//     redundant (each alternative already contains it).
//     Without the pairing, jFEX's four subjetEt variants (25/30/35/40) all match and the
//     selection returns 12 pairs with four indistinguishable jFEX curves.
//     PU200 only — at PU140 the only EtaSK seed available is the WTA cone one.
//         { "sample=ggF_hh_bbbb|sample=ttbar_allhad", "r16130", "_IOs_128_",
//           "rMerge_2", "_v3.root",
//           "Seed_gepWTAConeCellsTowersJets_EtaSK_subjetEt25GeV"
//           "|Seed_gFEXSRJ_EtaSK_subjetEt25GeV"
//           "|Seed_jFEXSRJ_EtaSK_subjetEt40GeV" }
//
// (3) SEEDED-CONE-ONLY (d_search disabled): v2 vs v3  [2 pairs, ggF, PU200]
//     v2 = 8 IOs, cone jets as BOTH input objects and seeds.
//     v3 = 128 IOs, towers as input objects, cone-jet seeds.
//     The two differ in IO type as well as count, so neither "_IO_..." nor a single
//     "_IOs_N_" can be pinned — the OR-group on the IO count is what spans them.
//     overlayMixesVersion/NIOs label the curves "v2"/"v3" and "IOs = 8"/"= 128".
//     PU200 only — no v2 / IOs=8 output exists at PU140.
//         { "sample=ggF_hh_bbbb", "r16130", "rMerge_0.001", "_EtaSK_",
//           "Seed_gepWTAConeCellsTowersJets", "_IOs_8_|_IOs_128_" }
//
// (4) PU140 vs PU200, nominal v3  [4 pairs: 2 pileups x 2 d_search, ggF]
//     The ACTIVE selection with the "r16130" entry REMOVED — dropping the pileup pin is
//     what lets both in. Legends then carry "<PU> = 140"/"= 200" per entry and the ATLAS
//     line reads "<PU> = 140, 200". Requires the --pu both list (as everything does).
//         { "sample=ggF_hh_bbbb", "_IOs_128_", "_IO_gepCellsTowers",
//           "Seed_gepWTAConeCellsTowersJets", "_EtaSK_", "_v3.root" }
//
// (5) PU SUPPRESSION: EtaSK vs SK vs NoSK, one pileup  [currently 2 pairs, not 3]
//     NO _NoSK_ output exists at either pileup as of 2026-08-25, so this yields EtaSK +
//     SK only. To get the third curve, set PU_SUPPRESSION = [False] in
//     condor/submit_jet_tagger_emulation.py and produce them first.
//         { "sample=ggF_hh_bbbb", "r16130", "_IOs_128_", "_IO_gepCellsTowers",
//           "Seed_gepWTAConeCellsTowersJets", "rMerge_2", "_v3.root",
//           "_EtaSK_|_SK_|_NoSK_" }
// ---------------------------------------------------------------------------------------

// =========================================================================================
// WHERE THE OVERLAY PDFs GO
// =========================================================================================
// "" (empty)  -> use the `overlaydir` line from the pair list, i.e. the submit script's
//                --label, which defaults to a timestamp like largeRJet_20260824_165506.
// "someName"  -> a bare name (no '/') becomes  overlayMultipleFiles/someName/
// "a/b/c/"    -> anything containing '/' is used verbatim as a path.
// A trailing '/' is added automatically.
//
// Name it after the STUDY so the directory is findable months later, e.g.
//     "pu140vs200_nominal_v3_128IOs"     matches the active kPlotSelect above
//     "ios128_vs_256_ggF_PU200"          mode (1)
//     "seedComparison_ggF_ttbar_PU200"   mode (2)
//     "seededConeOnly_v2_vs_v3_PU200"    mode (3)
// Per-file (non-overlay) PDFs are unaffected — they always go to
// largeRJetPlots/<config>/, named from the configuration itself.
//const std::string kPlotOverlayDir = "seededConeOnly_v2_vs_v3_PU200";
//const std::string kPlotOverlayDir = "Zprime";
//const std::string kPlotOverlayDir = "towerCut_T2_vs_T0_IOs256_ggF_PU200";
const std::string kPlotOverlayDir = "inputObjects_towerCut_PUsup_IOs_ggF_PU140";
//const std::string kPlotOverlayDir = "inputObjects_towerCut_PUsup_IOs_ggF_PU200";

// =========================================================================================
// DRAW ORDER — which pair is plotted first, second, ...
// =========================================================================================
// Applies to EVERY plot at once, because everything downstream keys off the pair index:
// draw order, colour from the Petroff palette, legend row order, and which curve owns the
// axes (the first one drawn).
//
// Entries are substrings matched exactly like kPlotSelect. A pair is ranked by the FIRST
// entry it contains; pairs matching none go last. The sort is STABLE, so pairs of equal
// rank keep their pair-list order — e.g. with the seed order below, d_search 0.001 still
// precedes d_search 2 within each seed.
//
// {} (empty) leaves the pair-list order alone, which is alphabetical by tagger filename:
// gFEXSRJ, then gepWTAConeCellsTowersJets, then jFEXSRJ. That is rarely the reading order
// you want, which is what this exists to fix.
//
// Current: the 7-arm input-object comparison. Baseline (_T2_, cut applied) first so it owns
// the axes and takes the first palette colour, then the six _T0_ arms in order of increasing
// pileup suppression — NoSK, SK, EtaSK — with 128 IOs before 256 within each. The IO count
// and the PU-suppression tag are not adjacent in the filename, so each entry spans kSeedMid.
// PU140 order: the cut-applied (_T2_) arms first so one of them owns the axes and the first
// palette colour, then the _T0_ arms, with 128 IOs before 256 within each group.
const std::vector<std::string> kPlotOrder = {
    "IOs_128" + kSeedMid + "_EtaSK_T2_",
    "IOs_256" + kSeedMid + "_EtaSK_T2_",
    "IOs_128" + kSeedMid + "_SK_T2_",
    "IOs_128" + kSeedMid + "_EtaSK_T0_",
    "IOs_256" + kSeedMid + "_EtaSK_T0_"
};
// PU200 order for the 7-arm study — restore alongside the PU200 selection above.
/*const std::vector<std::string> kPlotOrder = {
    "IOs_128" + kSeedMid + "_EtaSK_T2_",
    "IOs_128" + kSeedMid + "_NoSK_T0_",
    "IOs_256" + kSeedMid + "_NoSK_T0_",
    "IOs_128" + kSeedMid + "_SK_T0_",
    "IOs_256" + kSeedMid + "_SK_T0_",
    "IOs_128" + kSeedMid + "_EtaSK_T0_",
    "IOs_256" + kSeedMid + "_EtaSK_T0_"
};*/
// 2 GeV cut comparison, 2-arm version.
/*const std::vector<std::string> kPlotOrder = {
    "_T2_",
    "_T0_"
};*/
// Seed comparison order — cone jet -> jFEX -> gFEX.
/*const std::vector<std::string> kPlotOrder = {
    "Seed_gepWTAConeCellsTowersJets",
    "Seed_jFEXSRJ",
    "Seed_gFEXSRJ"
};*/
// ---------------------------------------------------------------------------------------

void largeRJetPlot(bool overlayThreeFiles = false,
                   const char* pairsFile = "largeRJetFilePairs.txt") {
    gLRJState.stage        = LRJStage::kPlot;
    lrj_file_pairs_path_   = pairsFile ? pairsFile : "";
    lrj_plot_select_       = kPlotSelect;
    lrj_plot_order_        = kPlotOrder;
    lrj_plot_overlay_dir_  = kPlotOverlayDir;
    largeRJetRun(overlayThreeFiles);
    gSystem->Exit(0);
}
